# Generated by Django 3.0.7 on 2020-07-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
